/**
 * Vite Dev Plugin — Content Pages
 *
 * Serves standalone content pages (/about/, /docs/*) during development.
 * In production, these pages are generated by scripts/build-content-pages.ts.
 *
 * The plugin intercepts matching routes, reads the corresponding markdown,
 * converts it to HTML via marked, and wraps it in the page-shell template.
 * CSS is linked to /styles/content.css which Vite processes through PostCSS.
 */

import * as fs from 'fs';
import * as path from 'path';
import { marked } from 'marked';
import type { Plugin } from 'vite';
import { buildRouteMap, renderSidebar } from './content-pages-config';

const routes = buildRouteMap();

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

export function contentPagesDevPlugin(): Plugin {
  let root: string;

  return {
    name: 'content-pages-dev',
    configResolved(config) {
      root = config.root;
    },
    configureServer(server) {
      // Runs before Vite's internal middleware
      server.middlewares.use(async (req, res, next) => {
        let url = req.url?.split('?')[0] ?? '';

        // Normalize: add trailing slash if missing
        if (url && !url.endsWith('/') && !path.extname(url)) {
          url += '/';
        }

        const route = routes[url];
        if (!route) return next();

        try {
          const contentDir = path.join(root, 'src/content');
          const templatePath = path.join(contentDir, 'templates/page-shell.html');
          const template = fs.readFileSync(templatePath, 'utf-8');

          const mdPath = path.join(contentDir, route.markdown);
          if (!fs.existsSync(mdPath)) {
            return next();
          }
          const mdSource = fs.readFileSync(mdPath, 'utf-8');
          const htmlContent = await marked.parse(mdSource);

          const hasSidebar = route.sidebarId != null;
          const sidebar = hasSidebar ? renderSidebar(route.sidebarId!) : '';
          const layoutClass = hasSidebar ? 'page-layout--with-sidebar' : '';
          const navAbout = route.activeNav === 'about' ? 'aria-current="page"' : '';
          const navDocs = route.activeNav === 'docs' ? 'aria-current="page"' : '';

          let html = template;
          html = html.replace(/\{\{title\}\}/g, route.title);
          html = html.replace(/\{\{description\}\}/g, route.description);
          html = html.replace(/\{\{canonical\}\}/g, url);
          html = html.replace(/\{\{css-href\}\}/g, '/styles/content.css');
          html = html.replace(/\{\{content\}\}/g, htmlContent);
          html = html.replace(/\{\{sidebar\}\}/g, sidebar);
          html = html.replace(/\{\{layout-class\}\}/g, layoutClass);
          html = html.replace(/\{\{nav-about\}\}/g, navAbout);
          html = html.replace(/\{\{nav-docs\}\}/g, navDocs);
          // No analytics in dev
          html = html.replace(/\{\{analytics\}\}/g, '');

          res.setHeader('Content-Type', 'text/html');
          res.statusCode = 200;
          res.end(html);
        } catch (err) {
          console.error(`[content-pages] Error serving ${url}:`, err);
          next();
        }
      });
    },
  };
}
