/**
 * Vite Dev Plugin — Content Pages
 *
 * Serves standalone content pages (/about/, /docs/*, /uk/about/, /uk/docs/*)
 * during development. In production, these pages are generated by
 * scripts/build-content-pages.ts.
 *
 * The plugin intercepts matching routes, reads the corresponding markdown,
 * converts it to HTML via marked, and wraps it in the page-shell template.
 * CSS is linked to /styles/content.css which Vite processes through PostCSS.
 */

import * as fs from 'fs';
import * as path from 'path';
import { marked } from 'marked';
import type { Plugin } from 'vite';
import {
  buildRouteMap,
  renderSidebar,
  localeStrings,
  DEFAULT_LOCALE,
  buildHreflangTags,
  langSwitchHref,
  findPageDef,
} from './content-pages-config';

const routes = buildRouteMap();

// ---------------------------------------------------------------------------
// Plugin
// ---------------------------------------------------------------------------

export function contentPagesDevPlugin(): Plugin {
  let root: string;

  return {
    name: 'content-pages-dev',
    configResolved(config) {
      root = config.root;
    },
    configureServer(server) {
      // Runs before Vite's internal middleware
      server.middlewares.use(async (req, res, next) => {
        let url = req.url?.split('?')[0] ?? '';

        // Normalize: add trailing slash if missing
        if (url && !url.endsWith('/') && !path.extname(url)) {
          url += '/';
        }

        // --- UK landing page ---
        if (url === '/uk/' || url === '/uk') {
          const landingPath = path.join(root, 'index.html');
          if (!fs.existsSync(landingPath)) return next();

          let html = fs.readFileSync(landingPath, 'utf-8');
          html = html.replace('<html lang="en">', '<html lang="uk">');
          html = html.replace(
            '<title>Syto — Data Wrangling in the Browser</title>',
            '<title>Syto — Обробка даних у браузері</title>'
          );
          html = html.replace(
            'content="Browser-based data wrangling tool for cleaning and transforming tabular data. No installation required."',
            'content="Браузерний інструмент для очищення та трансформації табличних даних. Не потребує встановлення."'
          );
          html = html.replace('>About</a>', '>Про Syto</a>');
          html = html.replace('>Docs</a>', '>Документація</a>');
          html = html.replace('>Tools</a>', '>Інструменти</a>');
          // CTA appears twice (nav + hero)
          html = html.replaceAll('>Open App</a>', '>Відкрити</a>');
          html = html.replace(
            /Data wrangling in the browser — clean, transform, and prepare your data without installing\s+anything\./,
            'Обробка даних у браузері — очищуйте, трансформуйте та готуйте дані без встановлення програм.'
          );
          html = html.replace(
            'href="/docs/" class="hero__link">Read the docs</a>',
            'href="/uk/docs/" class="hero__link">Документація</a>'
          );
          html = html.replace(
            'No installation, no accounts, no uploads. Your data stays in your browser.',
            'Без встановлення, без реєстрації, без завантаження на сервер. Ваші дані залишаються у вашому браузері.'
          );
          html = html.replace(
            'Syto — Data wrangling in the browser.',
            'Syto — Обробка даних у браузері.'
          );
          html = html.replace('>Open source</a>', '>Відкритий код</a>');
          html = html.replace('href="/about/"', 'href="/uk/about/"');
          html = html.replace('href="/docs/"', 'href="/uk/docs/"');
          html = html.replace(
            '<a href="/uk/" class="site-header__lang">UK</a>',
            '<a href="/" class="site-header__lang">EN</a>'
          );
          html = html.replace(
            'href="/" class="site-header__logo"',
            'href="/uk/" class="site-header__logo"'
          );

          res.setHeader('Content-Type', 'text/html');
          res.statusCode = 200;
          res.end(html);
          return;
        }

        const route = routes[url];
        if (!route) return next();

        try {
          const contentDir = path.join(root, 'src/content');
          const templatePath = path.join(contentDir, 'templates/page-shell.html');
          const template = fs.readFileSync(templatePath, 'utf-8');

          const mdPath = path.join(contentDir, route.markdown);
          if (!fs.existsSync(mdPath)) {
            return next();
          }
          const mdSource = fs.readFileSync(mdPath, 'utf-8');
          const htmlContent = await marked.parse(mdSource);

          const locale = route.locale;
          const strings = localeStrings[locale];
          const prefix = locale === DEFAULT_LOCALE ? '' : `/${locale}`;
          const page = findPageDef(route.markdown);

          const hasSidebar = route.sidebarId != null;
          const sidebar = hasSidebar ? renderSidebar(route.sidebarId!, locale) : '';
          const layoutClass = hasSidebar ? 'page-layout--with-sidebar' : '';
          const navAbout = route.activeNav === 'about' ? 'aria-current="page"' : '';
          const navDocs = route.activeNav === 'docs' ? 'aria-current="page"' : '';

          let html = template;
          html = html.replace(/\{\{lang\}\}/g, locale);
          html = html.replace(/\{\{title\}\}/g, route.title);
          html = html.replace(/\{\{description\}\}/g, route.description);
          html = html.replace(/\{\{canonical\}\}/g, url);
          html = html.replace(/\{\{hreflang-tags\}\}/g, page ? buildHreflangTags(page) : '');
          html = html.replace(/\{\{css-href\}\}/g, '/styles/content.css');
          html = html.replace(/\{\{content\}\}/g, htmlContent);
          html = html.replace(/\{\{sidebar\}\}/g, sidebar);
          html = html.replace(/\{\{layout-class\}\}/g, layoutClass);
          html = html.replace(/\{\{nav-about\}\}/g, navAbout);
          html = html.replace(/\{\{nav-docs\}\}/g, navDocs);
          html = html.replace(/\{\{home-href\}\}/g, prefix ? `${prefix}/` : '/');
          html = html.replace(/\{\{about-href\}\}/g, `${prefix}/about/`);
          html = html.replace(/\{\{docs-href\}\}/g, `${prefix}/docs/`);
          html = html.replace(/\{\{nav-about-label\}\}/g, strings.navAbout);
          html = html.replace(/\{\{nav-docs-label\}\}/g, strings.navDocs);
          html = html.replace(/\{\{tools-href\}\}/g, '/tools/json-to-csv/');
          html = html.replace(/\{\{nav-tools-label\}\}/g, strings.navTools);
          html = html.replace(/\{\{nav-cta-label\}\}/g, strings.navCta);
          html = html.replace(
            /\{\{lang-switch-href\}\}/g,
            page ? langSwitchHref(page, locale) : '/'
          );
          html = html.replace(/\{\{lang-switch-label\}\}/g, strings.langSwitcherLabel);
          html = html.replace(/\{\{footer-text\}\}/g, strings.footerText);
          html = html.replace(/\{\{footer-link-text\}\}/g, strings.footerLinkText);
          // No analytics in dev
          html = html.replace(/\{\{analytics\}\}/g, '');

          res.setHeader('Content-Type', 'text/html');
          res.statusCode = 200;
          res.end(html);
        } catch (err) {
          console.error(`[content-pages] Error serving ${url}:`, err);
          next();
        }
      });
    },
  };
}
